name: ecedi - Update Theme submodule

on:
  workflow_dispatch:
    inputs:
      submodule_path:
        required: true
        type: string

jobs:
  update-rennes-theme:
    uses: ecedi/rennes-ville-metropole-workflows/.github/workflows/ecedi-update-rennes-theme.yml@main
    secrets:
      ECEDI_PAT_TOKEN: ${{ secrets.ECEDI_PAT_TOKEN }}
